### PR TITLE
Get Query Headers and Define the output type : array or object

### PR DESCRIPTION
**Pull request by tomitomas**
I implement two functions :
- get the columns name of the last query -> call $_db->getLastQueryHeaders();
- define if the query type result has to be an array or an object $_db->setOutput('array' or 'object'); => usefull when you come from another project using mysql query like me and just want to modify you DB class with mysqli interface :+1:

### CODE REVIEW

**Comment by avbdr** [comment]
Great patch! 
1. What is the use of getLastQueryHeaders()?
2. Id rename _output var to _returnType with values Array and Object to be consistent with new dbObject.
3. Can you please update readme and add couple tests into tests/mysqlitests?

Thank you

**Comment by tomitomas** [comment]
Hello !

Thank you :)

1. I use it to display headers columns names on my page in table without modifying/verifying the data as the query is already having the good name :
```
$cols = Array ("id as 'my user ID'", "name as 'LAST NAME'", "email as 'EMAIL'");
$users = $db->get ("users", null, $cols);
if ($db->count > 0)
    print_r ($db->getLastQueryHeaders());
    foreach ($users as $user) { 
        print_r ($user);
    }
```
it will display 
```
my user ID       |      LAST NAME        |      EMAIL
1                |       toto            |      toto@toto.fr
...
```
I hope my explanation is understandable !?

2 & 3 => OKAY, np i'll do. 
If I find how :) cause it's the first time I use GIT here :)

**Comment by tomitomas** [comment]
sorry for the commit and revert, and commit and revert ... 
just trying to find out how git for windows works :)

hope everything is fine for you like that  !?

**Comment by tomitomas** [comment]
Do it sound okay for you !?

**Comment by avbdr** [comment]
i have implemented return type in a slightly different way to stay consistent with dbObject.
seems im missing some setter for a default returnType, but will commit it a bit later

**Pull request closed without merging**
