### PR TITLE
Better PHPDoc

### PR DESCRIPTION
**Pull request by canarslan12**
Unreachable/unused parts deleted
PHPDoc updated for some return/throws parts
Tab changed to 4 spaces

### CODE REVIEW

**Comment by avbdr** [comment]
can you please minimize the patch to only change doc part without changing code?

**Comment by avbdr** [comment]
thank you for the patch

**Comment by canarslan12** [comment]
what do you mean by changing code?
both unused ones and tab changes or just one of them?

**Comment by avbdr** [comment]
i mean to remove all the changes from the patch which are not related to the phpdoc

**Pull request closed without merging**
